```{r}
library(tidyverse)
library(lubridate)
source("../scripts/viridis.R")

data = map_dfr(2012:2022, ~{
  return ( read_csv(str_c("../data/nfl/play_by_play_", .x, ".csv")) )
})

```
### Introduction
What separates a super bowl winner from the rest? Are there any unique characteristics that are needed in order for a team to win the super bowl? In this analysis we seek to answer these questions by analyzing the super bowl winners from the last 10 years. Specifically we are looking at whether (blank variables) differ in super bowl winners compared to the rest of the NFL. 
 
 Question Interest: How does the average of blank variables of superbowl winners in the last ten years compare to the rest of the NFL?

### Background
We began the analysis by downloading the data from Github's "Awesome Public Datasets". NFL play-by-play data is accessed through r packages created specifically for analyzing NFL data. By installing the package "nflreadr", then using the function "load_pbp" we were able to view the play-by-play data for the last 10 seasons (2012-2022). Interestingly, there's an additional package called nflfastR available to efficiently access NFL data. Led by Sebastian Carl, he and 10 others published the two NFL packages in December 22, 2022 for NFLfastr and January 6, 2023. 
*discuss covid season*
What the variables mean
  Variable One
Air yards over yards after catch. This variable was constructed to represent the teams aggressiveness when they are backed up behind their own 30 yard line. Air yards represents the forward distance the ball travels in the air to the target. Yards after catch represents the forward distance the player travels after receiving the catch. Air yards divided by yards after catch will represent the teams willingness to be agressive when they are under pressure due to being backed up in their own territory. 
  Variable Two
This variable was constructed to represent defensive success-specifically in the red zone (less than 20 yards from the end zone). Tackles for loss is a good statistic to represent defensive success. The final variable is the tackles for loss when the opposing team is in the red zone divided by the tackles for loss when the opposing team is not in the red zone. The stat measures how good a team is in the red zone defensively compared to how they normally preform.
  Variable Three
Third down conversion rate
  Variable Four
Touchdowns per game  
What the rest of the paper entails
-running t test
### Analysis
# Third Down Conversion Rate

# Touchdowns

# Air Yards

# Defensive Tackles For Loss


### Discussion-Answer Questions of Interest

#Limitations

#Next Steps/Future Research

### References


